apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: user-service
  labels:
    app: userservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: hcorptech/userservice
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://159.89.171.87:25755/userservice"
            - name: OTHER_ENV_VARIABLE
              value: "value"

---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: user-service
spec:
  type: NodePort  
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
