apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: userservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
spec:
  type: NodePort
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
